### ISSUE TITLE
Right / left arrow keys don't work

### ISSUE THREAD

**Issue by josephernest** [asweigart/PyMsgBox#1]
If you do

    pymsgbox.prompt('What did you do today?')

and then write some text, and then do `Right arrow` or `Left arrow`, the the focus moves to the buttons (OK, Cancel), instead of allowing the cursor (caret) to move in the textbox.

**How to make that arrow keys let the user move inside the textbox?**

**Comment by asweigart** [comment]
Fixed in 1.0.4. Thanks!

**Comment by josephernest** [comment]
Thank you. If I remember well, I installed in on Windows with

    pip install pymsgbox

or something like this. Is there a command to update, directly from `pip` ? Thanks!

**Comment by asweigart** [comment]
Yes, you can run `pip install -U pymsgbox`
